/**
 * styles.js
 * All inline style objects for the TTS UI in one place.
 * Import the `S` object and use it in JSX: style={S.panel}
 */

export const S = {
    root: {
        minHeight: "100vh",
        background: "#0c0c0f",
        color: "#c8d0e8",
        fontFamily: "'Fira Mono','JetBrains Mono','Courier New',monospace",
        margin: 0,
        padding: 0,
        display: "flex",
        flexDirection: "column",
        alignItems: "center",
    },
    topBar: {
        width: "100%",
        borderBottom: "1px solid #1e2030",
        padding: "14px 32px",
        display: "flex",
        alignItems: "center",
        justifyContent: "space-between",
        background: "#0e0e14",
        boxSizing: "border-box",
    },
    logo: {
        fontSize: "13px",
        letterSpacing: "0.18em",
        color: "#7b9fff",
        textTransform: "uppercase",
        fontWeight: 700,
    },
    health: (ok) => ({
        display: "inline-flex",
        alignItems: "center",
        gap: "6px",
        fontSize: "11px",
        color: ok ? "#5af07e" : "#ff6b6b",
    }),
    dot: (ok) => ({
        width: 7,
        height: 7,
        borderRadius: "50%",
        background: ok ? "#5af07e" : "#ff6b6b",
        boxShadow: ok ? "0 0 6px #5af07e88" : "0 0 6px #ff6b6b88",
        animation: ok ? "pulse 2s infinite" : "none",
    }),
    main: {
        width: "100%",
        maxWidth: 760,
        padding: "40px 24px 80px",
        boxSizing: "border-box",
        display: "flex",
        flexDirection: "column",
        gap: 28,
    },
    heading: {
        fontSize: 22,
        fontWeight: 700,
        color: "#e4e8f8",
        letterSpacing: "0.05em",
        marginBottom: -10,
    },
    sub: {
        fontSize: 11,
        color: "#4a5070",
        letterSpacing: "0.15em",
        textTransform: "uppercase",
    },
    panel: {
        background: "#111118",
        border: "1px solid #1e2035",
        borderRadius: 8,
        padding: "20px 22px",
        display: "flex",
        flexDirection: "column",
        gap: 16,
    },
    label: {
        fontSize: 11,
        letterSpacing: "0.12em",
        textTransform: "uppercase",
        color: "#4a5070",
        marginBottom: 5,
        display: "block",
    },
    textarea: {
        width: "100%",
        minHeight: 120,
        background: "#0c0c0f",
        border: "1px solid #1e2035",
        borderRadius: 5,
        color: "#c8d0e8",
        fontFamily: "inherit",
        fontSize: 14,
        lineHeight: 1.6,
        padding: "12px 14px",
        resize: "vertical",
        outline: "none",
        boxSizing: "border-box",
        transition: "border-color 0.15s",
    },
    taFocus: { borderColor: "#3b4a7a" },
    row: { display: "flex", gap: 12, flexWrap: "wrap" },
    col: { display: "flex", flexDirection: "column", flex: 1, minWidth: 140 },
    select: {
        background: "#0c0c0f",
        border: "1px solid #1e2035",
        borderRadius: 5,
        color: "#c8d0e8",
        fontFamily: "inherit",
        fontSize: 13,
        padding: "9px 12px",
        outline: "none",
        cursor: "pointer",
        appearance: "none",
        backgroundImage: `url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='10' height='6'%3E%3Cpath d='M0 0l5 6 5-6z' fill='%234a5070'/%3E%3C/svg%3E")`,
        backgroundRepeat: "no-repeat",
        backgroundPosition: "right 12px center",
        paddingRight: 30,
    },
    toggleWrap: {
        display: "flex",
        alignItems: "center",
        gap: 10,
        cursor: "pointer",
        userSelect: "none",
    },
    track: (on) => ({
        width: 36,
        height: 20,
        borderRadius: 10,
        background: on ? "#7b9fff44" : "#1e2035",
        border: `1px solid ${on ? "#7b9fff" : "#2a2f50"}`,
        position: "relative",
        transition: "all 0.2s",
        flexShrink: 0,
    }),
    thumb: (on) => ({
        width: 14,
        height: 14,
        borderRadius: "50%",
        background: on ? "#7b9fff" : "#3a4060",
        position: "absolute",
        top: 2,
        left: on ? 18 : 2,
        transition: "left 0.2s",
        boxShadow: on ? "0 0 6px #7b9fff88" : "none",
    }),
    toggleLbl: {
        fontSize: 12,
        letterSpacing: "0.1em",
        textTransform: "uppercase",
        color: "#4a5070",
    },
    actionRow: { display: "flex", gap: 10, alignItems: "center", flexWrap: "wrap" },
    btn: (variant = "primary", disabled = false) => ({
        padding: "10px 24px",
        fontFamily: "inherit",
        fontSize: 12,
        letterSpacing: "0.12em",
        textTransform: "uppercase",
        fontWeight: 700,
        border: "none",
        borderRadius: 5,
        cursor: disabled ? "not-allowed" : "pointer",
        opacity: disabled ? 0.4 : 1,
        transition: "all 0.15s",
        ...(variant === "primary"
            ? { background: "#7b9fff", color: "#0c0c0f" }
            : variant === "danger"
                ? { background: "transparent", color: "#ff6b6b", border: "1px solid #ff6b6b44" }
                : { background: "transparent", color: "#7b9fff", border: "1px solid #7b9fff44" }),
    }),
    charCount: (over) => ({
        fontSize: 11,
        color: over ? "#ff6b6b" : "#2a3050",
        textAlign: "right",
        marginTop: -8,
    }),
    audioWrap: {
        background: "#0c0c0f",
        border: "1px solid #1e2035",
        borderRadius: 5,
        padding: "12px 14px",
    },
    metrics: { display: "flex", gap: 20, flexWrap: "wrap" },
    metric: { fontSize: 11, color: "#4a5070", letterSpacing: "0.08em" },
    mVal: { color: "#7b9fff", fontWeight: 700 },
    status: {
        fontSize: 12,
        color: "#4a5070",
        letterSpacing: "0.08em",
        minHeight: 18,
        padding: "2px 0",
    },
    error: {
        fontSize: 12,
        color: "#ff6b6b",
        background: "#200f0f",
        border: "1px solid #3a1515",
        borderRadius: 5,
        padding: "10px 14px",
    },
    infoBox: {
        fontSize: 11,
        color: "#4a5070",
        background: "#0e0e14",
        border: "1px solid #1e2035",
        borderRadius: 5,
        padding: "10px 14px",
        lineHeight: 1.7,
    },
};
